name: First Workflow

on:
  workflow_dispatch:
    inputs:
      dEnvironment:
        description: "Some environment"
        required: true
        default: "dev"

jobs:
  first_job:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
            echo "Hello World!"
            echo "New Line!"

      - name: Print goodbye
        run: echo "Goodbye!"

  hopefully_output_action:
    needs: first_job
    uses: ./.github/workflows/output.yml
    secrets: inherit
    with:
      dEnvironment: "test"
      sVariable: "Bole"
