name: Output Workflow

on:
  workflow_call:
    inputs:
      dEnvironment:
        description: "Desired environment"
        required: true
        type: string


jobs:
  result:

    runs-on: ubuntu-latest
    environment: ${{ dEnvironment }}
    steps:
      - name: Printing some information
        run: echo "Some information"

      - name: Print some secret
        run: echo "${{ secrets.TEST }}"