name: Output Workflow

on:
  workflow_call:
    inputs:
      dEnvironment:
        description: "Desired environment"
        required: true
        type: string
      sVariable:
        description: "Second variable"
        required: true
        type: string


jobs:
  result:

    runs-on: ubuntu-latest
    environment: ${{ inputs.dEnvironment }}
    steps:
      - name: Printing some information
        run: |
            echo ${{ inputs.sVariable }}
            echo $sVariable

      - name: Print some secret
        run: echo ${{ secrets.TEST }}