name: Output Workflow

on:
  workflow_call:
    inputs:
      dEnvironment:
        description: "Desired environment"
        required: true
        type: string
      sVariable:
        description: "Second variable"
        required: true
        type: string


jobs:
  result:

    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.dEnvironment }}
    steps:
      - name: Printing some information
        run: echo ${{ github.event.inputs.sVariable }}

      - name: Print some secret
        run: echo ${{ secrets.TEST }}