name: React Tests

on: [push, workflow_dispatch]

jobs:
  react_job_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  react_job_deploy:
    runs-on: ubuntu-latest
    needs: react_job_test
    steps:
      - name: Print message
        run: echo "Hello World"!